### ISSUE TITLE
LDAP userDn

### ISSUE THREAD

**Issue by a-chartier** [immobiliare/backstage-plugin-ldap-auth#107]
I noticed that the `userDn` value is hardcoded as such

```
 userDn: ldapEscape.dn`uid=${username},` + this.LDAPAuthOpts.userDn,
```

[here](https://github.com/immobiliare/backstage-plugin-ldap-auth/blob/next/packages/ldap-auth-backend/src/provider.ts#L99)

I know in my environment I needed to change  `uid` to `cn`. While `uid` is an attribute it's not part of the bind name for the user

Just wondering if it would be possible to add this as a variable so it's not hardcoded.

**Comment by simonecorsi** [comment]
Hey all 👋 

Just to give some update, we already have a way to inject both an `auth` and `search` function, but looking further at it after your feedback we saw some inconsistencies as how data is provided, we're fixing this in the same release of #106 and will release a new Major version this week 👍

**Comment by simonecorsi** [comment]
Hey :wave:

We've been busy lately but the release should be stable now! 

We took some of your feedback and reworked the plugin, in the new release ([v2.0.1](https://github.com/immobiliare/backstage-plugin-ldap-auth/releases/tag/v2.0.1)) you can add all connection configurations of [`ldap-authentication`](https://github.com/shaozi/ldap-authentication) in the [backstage configuration yaml](https://github.com/immobiliare/backstage-plugin-ldap-auth/tree/next/packages/ldap-auth-backend#connection-configuration), is should hopefully handle all use-cases.

If that's not enough, you can inject your [custom authentication function](https://github.com/immobiliare/backstage-plugin-ldap-auth/tree/next/packages/ldap-auth-backend#custom-authentication-function), this way you compose your authentication object programmatically if you have special cases!

I hope this fixes all your issues, I know I'm not so good with documentation so let me know if you need some extra info!

**Comment by a-chartier** [comment]
@simonecorsi 

Sorry for the late response I have been away and I am just getting back to this, I was testing this out but it doesn't seem to actually work. I am trying to dig into what it is going on.

Thanks for this update though it looks really good

**Comment by simonecorsi** [comment]
@a-chartier Let me know if we can help you out on this, at the moment you can pass all the options of [ldap-authentication](https://github.com/shaozi/ldap-authentication), maybe you can try to connect to your LDAP instance using that lib which is easier to test and then replicate on here, this could also help us check if there is a problem with an edge-case

**Comment by simonecorsi** [comment]
Marking as stale, let us know if anything changes.
