### ISSUE TITLE
Custom Auth implementation  Error 

### ISSUE THREAD

**Issue by paullally** [immobiliare/backstage-plugin-ldap-auth#286]
Hi I'm trying to implement your custom authentication function shown in the set-up example and I'm getting a few errors any advice would be greatly appreciated  

Thank you
![LdapAuth](https://user-images.githubusercontent.com/64094759/224009575-7a1c848f-ce85-4da1-8521-f3b109869aba.PNG)

**Comment by antoniomuso** [comment]
Can you post the errors?

**Comment by antoniomuso** [comment]
Ok, This is a bug. We forgot to pass auth function as input. I will fix it soon.

**Comment by antoniomuso** [comment]
@paullally, we have released the fix.

**Comment by simonecorsi** [comment]
[v3.0.1](https://github.com/immobiliare/backstage-plugin-ldap-auth/releases/tag/v3.0.1)
