### ISSUE TITLE
There is no LDAP configuration that matches

### ISSUE THREAD

**Issue by swood** [immobiliare/backstage-plugin-ldap-auth#384]
Hi.

I am trying to setup the LDAP auth plugin by the doc. 
My catalog.ts is:
>    builder.addEntityProvider(
>      LdapOrgEntityProvider.fromConfig(env.config, {
>        id: 'srv-ldap',
>        target: 'ldaps://srv.my.ldap.local:10636',
>        logger: env.logger,
>        schedule: env.scheduler.createScheduledTaskRunner({
>          frequency: { seconds: 25},
>          timeout: { seconds: 15},
>        }),
>      }),
>    );

My app-config.yaml is:
>auth:
>  environment: development
>  providers:
>    ldap:
>      development:
>        cookies:
>            secure: false # https cookies or not
>            field: 'backstage-token' # default
>        ldapAuthenticationOptions:
>          userSearchBase: 'ou=department,ou=users,dc=org,dc=com'
>          usernameAttribute: 'uid'
>          adminDn: 'uid=ro,ou=service accounts,dc=org,dc=com'
>          adminPassword: 'secret'
>          ldapOpts:
>            URL:
>              - 'ldaps://srv.my.ldap.local:10636'
>            tlsOptions:
>              rejectUnauthorized: false

Then I am getting the next error:

>2023-05-15T15:58:05.214Z backstage info Found 3 new secrets in config that will be redacted
>2023-05-15T15:58:05.220Z backstage info Created UrlReader >predicateMux{readers=azure{host=dev.azure.com,authed=false},bitbucketCloud{host=bitbucket.org,authed=false},github{host=>github.com,authed=false},gitlab{host=gitlab.ikarem.io,authed=true},gitlab{host=gitlab.com,authed=false},awsS3{host=amazonaw>s.com,authed=false},fetch{}
>Backend failed to start up TypeError: There is no LDAP configuration that matches "ldaps://srv.my.ldap.local:10636". Please add a >configuration entry for it under "ldap.providers".
>    at Function.fromConfig (/root/backstage/backstage-app/node_modules/@backstage/plugin-catalog-backend-module->ldap/dist/index.cjs.js:778:13)
>    at createPlugin (webpack-internal:///./src/plugins/catalog.ts:17:128)
>    at async main (webpack-internal:///./src/index.ts:90:31)

Can you please help why? I've installed the backend plugin. However, it seems it doesn't work at all.

**Comment by antoniomuso** [comment]
The variable `URL` is not in uppercase but in lowercase: `url`
