### ISSUE TITLE
Example code not working

### ISSUE THREAD

**Issue by moley** [immobiliare/backstage-plugin-ldap-auth#423]
Hi to all, 

I am trying to use ldp authentication following this example: 
https://github.com/immobiliare/backstage-plugin-ldap-auth/blob/main/packages/ldap-auth-backend/README.md

My problem: 
* It does not work but I get no sensible error in logfile
* In line `tokenValidator: new JWTTokenValidator(new Keyv()),` I recieve 

> TS2322: Type 'JWTTokenValidator' is not assignable to type 'AuthProviderFactory'.   Type 'JWTTokenValidator' provides no match for the signature '(options: { providerId: string; globalConfig: AuthProviderConfig; config: Config; logger: Logger; resolverContext: AuthResolverContext; }): AuthProviderRouteHandlers'.

but I do not know if this is part of the problem because yarn dev compiles

* If I want to add "Custom checks if user exists" just to have a point were I can add a breakpoint when debugging I recieve 

> TS2322: Type '{ checkUserExists(ldapAuthOptions: any, searchFunction: any): Promise<boolean>; }' is not assignable to type 'AuthProviderFactory'.   Object literal may only specify known properties, and 'checkUserExists' does not exist in type 'AuthProviderFactory

I am using backstage 1.14.2 with 
  "@backstage/plugin-auth-backend": "^0.18.3",
  "@backstage/plugin-auth-node": "^0.2.14",
  "@immobiliarelabs/backstage-plugin-ldap-auth-backend": "^3.0.1",
  "@immobiliarelabs/backstage-plugin-ldap-auth": "^3.0.1",

So my question: how can I determine and solve the problem without any entrance point of debugging?

Would be nice if you can help me
Thanks in advance

**Comment by moley** [comment]
Hello together, 

anybody who could give me a hint or help out?
Are infos missing to answer my question?

Cheers
Markus

**Comment by moley** [comment]
Any life in this project?

**Comment by antoniomuso** [comment]
Can you post your code? It seems that you are passing the variable to the wrong function.

**Comment by moley** [comment]
Hi anoniomuso, 
thanks for your reply, yes, it is like mentioned, taken 1:1 from example, here: 
<img width="600" alt="grafik" src="https://github.com/immobiliare/backstage-plugin-ldap-auth/assets/3918367/25964787-2081-4b9e-be79-93722b28816c">

**Comment by moley** [comment]
<img width="1015" alt="grafik" src="https://github.com/immobiliare/backstage-plugin-ldap-auth/assets/3918367/9e5fe902-be3c-4ff6-b00b-1ff1c9d36ee8">

**Comment by antoniomuso** [comment]
TokenValidator should be passed as input to the `create` function. [see](https://github.com/immobiliare/backstage-plugin-ldap-auth/blob/main/examples/jwt-token-store-postgres.md)
