### ISSUE TITLE
Spaces in password

### ISSUE THREAD

**Issue by pleroux-bell** [immobiliare/backstage-plugin-ldap-auth#507]
Hi,
We are currently using your plugin to perform LDAP authentication and we were wondering why spaces weren't allowed in the password?

I know it is done through the [Line32 of the Form.tsx](https://github.com/immobiliare/backstage-plugin-ldap-auth/blob/3f04a185de254d23604c7781869d9ccee1f73c6f/packages/ldap-auth/src/components/LoginPage/Form.tsx#L32).

We have users who do have spaces in their usernames and this is causing them to be unable to log in.

Thanks!

**Comment by antoniomuso** [comment]
Yes, it is a thing that can be removed! Could you do a PR to remove it?

**Comment by pleroux-bell** [comment]
Thanks you! I completely missed that
