### ISSUE TITLE
Using ldap-auth-backend with the new backend-system

### ISSUE THREAD

**Issue by oliverdirks** [immobiliare/backstage-plugin-ldap-auth#544]
Hey, 

the new backend systems looks very cool and gets more and more support with every update of Backstage. 
Is there any plan to migrate the plugin?

Cheers 
Olli

**Comment by antoniomuso** [comment]
Yes, sure, we scheduled to work on it. However, this plugin requires a not little effort to migrate.

**Comment by antoniomuso** [comment]
Now the version [v4.1.0](https://github.com/immobiliare/backstage-plugin-ldap-auth/releases/tag/v4.1.0) support the new backend system.
