### ISSUE TITLE
User logs out upon refreshing the backstage application in two distinct browsers

### ISSUE THREAD

**Issue by veerendervoskula** [immobiliare/backstage-plugin-ldap-auth#608]
Thank you for the amazing LDAP plugin. It meets most of our needs.
I'd want to raise an issue with relation to storing tokens in Postgres while initializing **JWTTokenValidator** as seen below.
```

 const tokenValidator: TokenValidator | undefined = new JWTTokenValidator(
        new Keyv(
            postgresURL,
            { table: 'token' }
        )
  );
```
 

To reproduce the issue, open the backstage application in two different browsers.

**Reproducing steps:-**

1)Use a browser such as Firefox to log in to the backstage application using the LDAP user and password.
2)Once the login is successful in the preceding step, repeat the process in another browser, such as Chrome, by logging in to the backstage application using the LDAP user and password.
3)Refresh the Firefox browser to initiate a refresh API call.
4)When the Chrome browser is refreshed, a refresh API request is executed, resulting in a JWT EXPIRED TOKEN error and returning the user to the login screen.

During the iat < invalidBeforeDate validation check  https://github.com/immobiliare/backstage-plugin-ldap-auth/blob/feccc188cc293ac953e02852b4a22e0e7b7b2933/packages/ldap-auth-backend/src/jwt.ts#L63 
, iat value of the refreshed token in chrome browser indicating that it is always less than invalidBeforeDate.

This forces users to login regularly when they refresh the program in two distinct browsers.

Is there a way to store the token with distinct **sub** value so that it satisfies user login in distinct browsers?

**Comment by antoniomuso** [comment]
hi @veerendervoskula, you can removing this line of code overwriting the code: 
```ts
import {
  JWTTokenValidator,
  normalizeTime,
  parseJwtPayload,
} from '@immobiliarelabs/backstage-plugin-ldap-auth-backend';

class TokenValidatorCustom extends JWTTokenValidator {
  async isValid(jwt: string): Promise<boolean> {
    const { exp } = parseJwtPayload(jwt);

    if (
        normalizeTime(Date.now()) >
        exp + normalizeTime(this.increaseTokenExpireMs)
    ) {
        // is expired?
        throw new Error("Token expired");
    }

    return true;
  }
}
```
In this way you skip the invalidation.

**Comment by veerendervoskula** [comment]
The above suggestion works. Thank you for your input @antoniomuso ; closing the ticket.
