### ISSUE TITLE
Request: ability to show error message on login error and to keep the login state

### ISSUE THREAD

**Issue by hubofgitongithub** [immobiliare/backstage-plugin-ldap-auth#614]
Hey, first of all: thanks for writing the plugin!

In our usage we are currently missing two things when a user fails to login:

- the ability to set a clear error message. There is a way to provide a `helperTextPassword` and `helperTextUsername`, but no way to detect if there has been an error logging in when implementing the plugin. Currently the fields only become red underlined, which is a missed opportunity to better inform the user.

- to keep the state of the login form. Currently when someone fails to login the form resets.

Let me know if help is needed with implementation.

**Comment by antoniomuso** [comment]
Hi @hubofgitongithub, thanks for using the plugin. It looks like a good feature. Have you time to add it? Otherwise, I will pick up later.

**Comment by antoniomuso** [comment]
@hubofgitongithub, yes, we know. Currently, the front-end plugin misses tests and code to check the effectivity functionalities.

**Comment by antoniomuso** [comment]
This feature is now supported thanks to https://github.com/immobiliare/backstage-plugin-ldap-auth/commit/84941fae0c1d42e82edda5872dfd37ca5970666e
