### ISSUE TITLE
Request: upgrade deps and support MUI 5 for ldap-auth package 

### ISSUE THREAD

**Issue by hubofgitongithub** [immobiliare/backstage-plugin-ldap-auth#615]
This project uses relatively old dependencies. Backstage for instance now supports MUI 5.

Request:
- upgrade backstage/theme package
- use MUI 5 type of styling (either [sx prop](https://mui.com/material-ui/customization/how-to-customize/#the-sx-prop) or [a reusable component](https://mui.com/material-ui/customization/how-to-customize/#2-reusable-component))
- update peerdependency to include react 18

**Comment by antoniomuso** [comment]
It does not make sense to migrate to mui5 until Backstage does a complete migration
