### ISSUE TITLE
New backend system?

### ISSUE THREAD

**Issue by sebastianslutzky** [immobiliare/backstage-plugin-ldap-auth#667]
Hi,
I am migrating my backend to the new backend system. 
All plugins work (using the [LegacyPlugin](https://backstage.io/docs/backend-system/building-backends/migrating/) function)
except my LDAP auth plugin.

Do you have a code example on how to use it with the new backend system?
txs

**Comment by sebastianslutzky** [comment]
actually, I've found the document in your website for the new backend
However, I've tried it and it didn't work.
the front end is calling for auth/ldap/refresh as before, but now I am receiving 404 for that call. It looks like some part of the backend is meant to add that route but is no longer doing it.
would you please be able to help?
thanks

**Comment by antoniomuso** [comment]
Have you update both backend and frontend plugin to the same and last version ?

**Comment by Jincoco88912** [comment]
I have the same issue too, got a 404 error on auth/ldap/refresh.

**Comment by sebastianslutzky** [comment]
hi @antoniomuso . apologies for the delay. I am using 4.2.0 for both backend and frontend

**Comment by sebastianslutzky** [comment]
@antoniomuso is /api/auth/ldap/refresh supposed to be missing? or is it obsolete in the latest version?

**Comment by antoniomuso** [comment]
Are you using the last Backstage version? As you can see, `refresh` works in the tests. Can you post your plugin configuration?

**Comment by gbranco** [comment]
Hello, seems like i'm facing the same issue

My steps:
- Create a new backstage application using the latest cli version (shows `1.27.0` in backstage.json)
- Config the ldap backend
- Setup ldap-auth

```
    auth:
        environment: production # eg: production|staging|review|develop
        providers:
            ldap:
                # eg: production|staging|review|develop
                production:
                    cookies:
                        secure: false # https cookies or not
                        field: 'backstage-token' # default
    
                    ldapAuthenticationOptions:
                        userSearchBase: 'ou=users,dc=ns,dc=farm' # REQUIRED
                        # what is the user unique key in your ldap instance
                        usernameAttribute: 'uid' # defaults to `uid`
                        # directory where to search user
                        # default search will be `[userSearchBase]=[username],[userSearchBase]`
    
                        # User able to list other users, this is used
                        # to check incoming JWT if user are already part of the LDAP
                        # NOTE: If no admin user/pass provided we'll attempt a credential-less search
                        adminDn: uid={ADMIN_USERNAME},ou=users,dc=ns,dc=farm
                        adminPassword: '{ADMIN_CRED}'
    
                        ldapOpts:
                            url:
                                - '{LDAPS_HOST}'
                            tlsOptions:
                                rejectUnauthorized: false
``` 

- Then `yarn dev`

As a I try to login I get : 404 from /refresh endpoint

Checking the 404 response under `'/api/auth/ldap/refresh'` I have a message

```
{
"error": {
  "name": "NotFoundError",
  "message": "Auth provider registered for 'ldap' is misconfigured. This could mean the configs under auth.providers.ldap are missing or the environment variables used are not defined. Check the auth backend plugin logs when the backend starts to see more details.",
  "stack": "NotFoundError: Auth provider registered for 'ldap' is misconfigured. This could mean the configs under auth.providers.ldap are missing or the environment variables used are not defined. Check the auth backend plugin logs when the backend starts to see more details.\n    at ..."
},
"request": {
  "method": "POST",
  "url": "/api/auth/ldap/refresh"
},
"response": {
  "statusCode": 404
  }
}
``` 

And I could not figure out if something is miconfigured :/

Some additional information for context:

- I had it working using the old backend system using the same values for configuration
- Ldap connection is working using the same values for the catalog provider 

Any advice?

**Comment by Jenson3210** [comment]
As seen in [backstage documentation](https://backstage.io/docs/backend-system/building-backends/migrating/#auth-plugin-modules-and-their-resolvers), I missed to add `backend.add(import('@backstage/plugin-auth-backend'));`. 
Adding it fixed my 404 on the refresh. 
It's not mentioned in the readme here. 

next issue I had was a misunderstanding from [this comment](https://github.com/immobiliare/backstage-plugin-ldap-auth/blob/main/packages/ldap-auth-backend/README.md?plain=1#L134). It should've been 

In the startup logs, there should be a log line that mentions the used plugins like: 
```
rootHttpRouter info Listening on :7007 
backstage info Plugin initialization started: 'proxy', 'catalog', 'search', 'auth', 'techdocs', 'kubernetes' type=initialization
```
For me the auth plugin was not present in the list.
