### ISSUE TITLE
Password field is not contained in a form:

### ISSUE THREAD

**Issue by moley** [immobiliare/backstage-plugin-ldap-auth#822]
Hello, 

I am using your LDAP plugin, which works very well. Thank you for contributing. 
One thing I noticed.... In Chrome I recieve in console log a 

Password field is not contained in a form: (More info: https://goo.gl/9p2vKq) 
_`<input aria-invalid="false" id="password" required="" type="password" class="MuiInputBase-input-446 MuiInput-input-434 MuiInputBase-inputMarginDense-447 MuiInput-inputMarginDense-435" value="MY_PASSWORD">`_

were my password is shown in the developer console.
I am currently one minor version behind using "@immobiliarelabs/backstage-plugin-ldap-auth": "^4.2.0"

Is there any possibility for me to fix or does this have to be fixed within the plugin? 
Would be nice to get feedback, Thanks

**Comment by antoniomuso** [comment]
Hi @moley, thank you for the issue. Nice to know; we will fix it at soon as possible!

**Comment by antoniomuso** [comment]
Closed by: https://github.com/immobiliare/backstage-plugin-ldap-auth/pull/823

**Comment by moley** [comment]
wow, this was near lightspeed - thank you for the prompt fix, I will test it
